version: '3.8'

services:
  db-workcraft:
    container_name: db-workcraft
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=workcraft_api
      - POSTGRES_PASSWORD=!B48EWBNKGg!
      - POSTGRES_USER=api-platform
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  
  php-workcraft:
    container_name: php-workcraft
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/workcraft
    depends_on:
      - db-workcraft
  
  nginx:
    container_name: nginx-workcraft
    build:
      context: ./nginx
    volumes:
      - ./app/:/var/www/workcraft
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
#      - ./nginx-prod/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx-prod/certs/:/etc/nginx/conf.d/certs/
#      - ./nginx-prod/sites/:/etc/nginx/sites-available
#      - ./nginx-prod/conf.d/:/etc/nginx/conf.d/
#      - ./logs:/var/log/nginx/
    depends_on:
      - php-workcraft
    ports:
      - "80:80"
      - "443:443"
volumes:
  postgres-db-workcraft-data: